// new/src/components/Header.svelte
<script>
  import { scale } from 'svelte/transition';
  import { cubicIn, cubicOut } from 'svelte/easing';

  let showMenu = false;

  function handleClick() {
    console.log(showMenu);
    showMenu = !showMenu;
  }
</script>

<header class="relative bg-black-lighter md:flex-auto md:h-full md:px-8">
  <div class="flex justify-between items-center px-4 pt-6 pb-4 sm:px-6 md:flex-col md:h-full">
    <div class="">
      <a href="#1" class="flex md:px-4 md:py-4">
        <img
          class="h-8 w-auto sm:h-16"
          src="https://tailwindui.com/img/logos/workflow-mark-on-white.svg"
          alt="Workflow" />
      </a>
    </div>
    <div class="-mr-2 -my-2 md:hidden ">
      <button
        type="button"
        on:click={handleClick}
        class="inline-flex items-center justify-center p-2 rounded-md text-white-dark hover:text-white-light focus:outline-none focus:text-white-light transition duration-150 ease-in-out">
        <!-- Heroicon name: menu -->
        <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
        </svg>
      </button>
    </div>
    <nav class="hidden whitespace-no-wrap text-white-dark md:flex md:pt-16 md:flex-col md:items-start">
      <a
        href="#1"
        class="-m-3 p-6 flex items-center space-x-4 rounded-lg hover:text-white-light focus:text-white-light transition ease-in-out duration-150 text-base leading-6 font-medium text-gray-900 text-white-light">
        Inicio
      </a>
      <a
        href="#1"
        class="-m-3 p-6 flex items-center space-x-4 rounded-lg hover:text-white-light focus:text-white-light transition ease-in-out duration-150 text-base leading-6 font-medium text-gray-900">
        Sobre Nosotros
      </a>
      <a
        href="#1"
        class="-m-3 p-6 flex items-center space-x-4 rounded-lg hover:text-white-light focus:text-white-light transition ease-in-out duration-150 text-base leading-6 font-medium text-gray-900">
        ¿Por qué elegirnos?
      </a>
      <a
        href="#1"
        class="-m-3 p-6 flex items-center space-x-4 rounded-lg hover:text-white-light focus:text-white-light transition ease-in-out duration-150 text-base leading-6 font-medium text-gray-900">
        Precios
      </a>
      <a
        href="#1"
        class="-m-3 p-6 flex items-center space-x-4 rounded-lg hover:text-white-light focus:text-white-light transition ease-in-out duration-150 text-base leading-6 font-medium text-gray-900">
        Gallería
      </a>
      <a
        href="#1"
        class="-m-3 p-6 flex items-center space-x-4 rounded-lg hover:text-white-light focus:text-white-light transition ease-in-out duration-150 text-base leading-6 font-medium text-gray-900">
        Testimonios
      </a>
      <a
        href="#1"
        class="-m-3 p-6 flex items-center space-x-4 rounded-lg hover:text-white-light focus:text-white-light transition ease-in-out duration-150 text-base leading-6 font-medium text-gray-900">
        Pedir cita
      </a>
    </nav>
    <div class="hidden md:inline-block md:mt-auto md:text-white-gray">
      <a href="#1">Instagram </a>
      <a href="#1"> Facebook </a>
    </div>
  </div>
  {#if showMenu}
    <div
      in:scale={{ duration: 200, start: 0.95, easing: cubicIn }}
      out:scale={{ duration: 200, start: 0.95, easing: cubicOut }}
      class="absolute top-0 inset-x-0 p-2 transition transform origin-top-right md:hidden">
      <div class="rounded-lg shadow-lg">
        <div class="rounded-lg shadow-xs bg-black-dark text-white-dark divide-y-2 divide-gray-50">
          <div class="pt-5 pb-6 px-5 space-y-6">
            <div class="flex items-center justify-between">
              <div>
                <img
                  class="h-8 w-auto"
                  src="https://tailwindui.com/img/logos/workflow-mark-on-white.svg"
                  alt="Workflow" />
              </div>
              <div class="-mr-2">
                <button
                  on:click={handleClick}
                  type="button"
                  class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white-light focus:outline-none focus:text-white-light transition duration-150 ease-in-out">
                  <svg
                    class="h-6 w-6"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            </div>
            <div>
              <nav class="grid grid-cols-1 gap-7">
                <a
                  href="#1"
                  class="-m-3 p-3 flex items-center space-x-4 rounded-lg hover:bg-gray-50 transition ease-in-out duration-150 text-base leading-6 font-medium text-gray-900 text-white-light">
                  Inicio
                </a>
                <a
                  href="#1"
                  class="-m-3 p-3 flex items-center space-x-4 rounded-lg hover:bg-gray-50 transition ease-in-out duration-150 text-base leading-6 font-medium text-gray-900">
                  Sobre Nosotros
                </a>
                <a
                  href="#1"
                  class="-m-3 p-3 flex items-center space-x-4 rounded-lg hover:bg-gray-50 transition ease-in-out duration-150 text-base leading-6 font-medium text-gray-900">
                  ¿Por qué elegirnos?
                </a>
                <a
                  href="#1"
                  class="-m-3 p-3 flex items-center space-x-4 rounded-lg hover:bg-gray-50 transition ease-in-out duration-150 text-base leading-6 font-medium text-gray-900">
                  Precios
                </a>
                <a
                  href="#1"
                  class="-m-3 p-3 flex items-center space-x-4 rounded-lg hover:bg-gray-50 transition ease-in-out duration-150 text-base leading-6 font-medium text-gray-900">
                  Gallería
                </a>
                <a
                  href="#1"
                  class="-m-3 p-3 flex items-center space-x-4 rounded-lg hover:bg-gray-50 transition ease-in-out duration-150 text-base leading-6 font-medium text-gray-900">
                  Testimonios
                </a>
                <a
                  href="#1"
                  class="-m-3 p-3 flex items-center space-x-4 rounded-lg hover:bg-gray-50 transition ease-in-out duration-150 text-base leading-6 font-medium text-gray-900">
                  Pedir cita
                </a>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  {/if}
</header>

// src/components/Header/index.tsx
import React, { useState } from 'react'
import Transition from '../Transition'

const Header = () => {
  const [showDialog, setShowDialog] = useState(false)
  const displayDialog = () => {
    setShowDialog(true)
  }

  const hideDialog = () => {
    setShowDialog(false)
  }
  return (
    <div className="pt-notch relative bg-gray-800 pt-6">
      <nav className="h-16 relative max-w-screen-xl mx-auto flex items-center justify-between px-4 sm:px-6">
        <div className="notch flex items-center flex-1">
          <div className="flex items-center justify-between w-full md:w-auto">
            <a
              className="flex items-center"
              href="/"
              title="Ir a página de inicio"
            >
              <picture>
                <source srcSet="/logo.webp" type="image/webp" />
                <img className="h-8 w-auto sm:h-10" src="/logo.jpg" alt="" />
              </picture>
            </a>
            <div className="-mr-2 flex items-center md:hidden">
              <button
                onClick={displayDialog}
                type="button"
                aria-label="Abrir menu del listado de páginas"
                className="inline-flex items-center justify-center p-2 rounded-md text-gray-500 hover:text-gray-50 hover:bg-gray-500 focus:outline-none focus:bg-gray-100 focus:text-gray-50 transition duration-150 ease-in-out"
              >
                <svg
                  className="h-6 w-6"
                  stroke="currentColor"
                  fill="none"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M4 6h16M4 12h16M4 18h16"
                  />
                </svg>
              </button>
            </div>
          </div>
          <div className="hidden md:block md:ml-10">
            <a
              href="/book"
              title="Pedir cita"
              className="ml-10 font-medium text-gray-500 hover:text-gray-100 focus:outline-none focus:text-gray-100 transition duration-150 ease-in-out"
            >
              Pedir cita
            </a>
            <a
              href="/pricing"
              title="Ver lista de precios de la peluqueria"
              className="ml-10 font-medium text-gray-500 hover:text-gray-100 focus:outline-none focus:text-gray-100 transition duration-150 ease-in-out"
            >
              Lista de precios
            </a>
            <a
              href="/work"
              title="Ver trabajos realizados"
              className="ml-10 font-medium text-gray-500 hover:text-gray-100 focus:outline-none focus:text-gray-100 transition duration-150 ease-in-out"
            >
              Trabajos realizados
            </a>
            <a
              href="/contact"
              title="Formulario de contacto"
              className="ml-10 font-medium text-gray-500 hover:text-gray-100 focus:outline-none focus:text-gray-100 transition duration-150 ease-in-out"
            >
              Contacto
            </a>
          </div>
        </div>
      </nav>
      <Transition
        show={showDialog}
        enter="duration-150 ease-out"
        enterFrom="opacity-0 scale-95"
        enterTo="opacity-100 scale-100"
        leave="duration-100 ease-in"
        leaveFrom="opacity-100 scale-100"
        leaveTo="opacity-0 scale-95"
      >
        <div className="absolute top-0 z-40 inset-x-0 p-2 transition transform origin-top-right md:hidden">
          <div className="rounded-lg shadow-md">
            <div className="rounded-lg bg-gray-800 shadow-xs overflow-hidden">
              <div className="px-5 pt-4 flex items-center justify-between">
                <div>
                  <a
                    className="flex items-center"
                    href="/"
                    title="Ir a página de inicio"
                  >
                    <picture>
                      <source srcSet="/logo.webp" type="image/webp" />
                      <img
                        className="h-8 w-auto sm:h-10"
                        src="/logo.jpg"
                        alt=""
                      />
                    </picture>
                  </a>
                </div>
                <div className="-mr-2">
                  <button
                    onClick={hideDialog}
                    type="button"
                    aria-label="Cerrar menu del listado de páginas"
                    className="inline-flex items-center justify-center p-2 rounded-md text-gray-500 hover:text-gray-50 hover:bg-gray-500 focus:outline-none focus:bg-gray-100 focus:text-gray-50 transition duration-150 ease-in-out"
                  >
                    <svg
                      className="h-6 w-6"
                      stroke="currentColor"
                      fill="none"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M6 18L18 6M6 6l12 12"
                      />
                    </svg>
                  </button>
                </div>
              </div>
              <div className="px-2 pt-2 pb-3">
                <a
                  href="/book"
                  title="Pedir cita"
                  className="mt-1 block px-3 py-2 rounded-md text-base font-medium text-gray-500 hover:text-gray-50 hover:bg-gray-500 focus:outline-none focus:bg-gray-100 focus:text-gray-50 transition duration-150 ease-in-out"
                >
                  Pedir cita
                </a>
                <a
                  href="/pricing"
                  title="Ver lista de precios de la peluqueria"
                  className="mt-1 block px-3 py-2 rounded-md text-base font-medium text-gray-500 hover:text-gray-50 hover:bg-gray-500 focus:outline-none focus:bg-gray-100 focus:text-gray-50 transition duration-150 ease-in-out"
                >
                  Lista de precios
                </a>
                <a
                  href="/work"
                  title="Ver trabajos realizados"
                  className="mt-1 block px-3 py-2 rounded-md text-base font-medium text-gray-500 hover:text-gray-50 hover:bg-gray-500 focus:outline-none focus:bg-gray-100 focus:text-gray-50 transition duration-150 ease-in-out"
                >
                  Trabajos realizados
                </a>
                <a
                  href="/contact"
                  title="Formulario de contacto"
                  className="mt-1 block px-3 py-2 rounded-md text-base font-medium text-gray-500 hover:text-gray-50 hover:bg-gray-500 focus:outline-none focus:bg-gray-100 focus:text-gray-50 transition duration-150 ease-in-out"
                >
                  Contacto
                </a>
              </div>
            </div>
          </div>
        </div>
      </Transition>
    </div>
  )
}

export default Header
